apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-chat-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-chat-deployment
  maxReplicas: 10 # define max replica count
  minReplicas: 3  # define min replica count
  targetCPUUtilizationPercentage: 50