apiVersion: v1  # 
kind: Service       # ServiceTypes 
metadata:              # Attributes related to  config
  name: spring-chat-service   # name 
spec:
  type: NodePort           
  selector:     # service targets is defined with a label selector
    app: wecloud-chat
  ports:    
    - protocol: TCP   # protocol
      port: 80            #  request port
      targetPort: 8080 # port listens to